const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';
const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export default {
    LOAD_ARTICLES_REQUEST,
    LOAD_ARTICLES_SUCCESS,
    LOAD_ARTICLES_FAILURE,
    GET_ARTICLE_REQUEST,
    GET_ARTICLE_SUCCESS,
    GET_ARTICLE_FAILURE
};
