const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export default {
    LOAD_ARTICLES_REQUEST,
    LOAD_ARTICLES_SUCCESS,
    LOAD_ARTICLES_FAILURE
};
